[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/galeria"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/cennik"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/kontakt"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/nasze-osrodki"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/rezerwacja"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200