// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uayyuyplstjgnrnnlgyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVheXl1eXBsc3RqZ25ybm5sZ3lrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxOTA0NjAsImV4cCI6MjA3MDc2NjQ2MH0.M_t93ZWp25cux_Hpzkp07ffvWe4BTXfxMW4am6QTQUY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});